config/routes.rb
Rails.application.routes.draw do
  namespace :shopify_app do
    post 'webhooks/receive_customer_create_params'
    post 'webhooks/delete_customer'
    post 'webhooks/order_create'
    
  
  end
  post '/customers/updateinfo',to: "customers#updateinfo"
  resources :coupons
  resources :faq
  resources :customers do
    collection {post :import}
  end
  resources :settings
  root :to => 'home#index'
  get 'home/check_status_of_charge_activation',to: "home#check_status_of_charge_activation"
  get 'billings/check_status_of_charge_activation', to: "billings#check_status_of_charge_activation"
  post '/app_proxy/checkings/check_customer_dob_present', to: "checkings#check_customer_dob_present"
  post '/app_proxy/checkings/check_customer_dob_present_and_update', to: "checkings#check_customer_dob_present_and_update"
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coupon.rb
class Coupon < ApplicationRecord
	belongs_to :customer
	belongs_to :shop
	#validates_numericality_of :setting.day_number, :greater_than_or_equal_to => 1
	validate :non_zero

	def non_zero
		if self.day_number == 0
		   self.errors.add(:day_number, "Field can't be zero")
		end
	end
end

app/controllers/coupons_controller.rb
class CouponsController < ShopifyApp::AuthenticatedController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:coupon_code, :shop_id, :is_redeem, :customer_id)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= form_with(model: coupon, local: true) do |form| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coupon_code %>
    <%= form.number_field :coupon_code %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.hidden_field :shop_id,value: form.shop_id %>
  </div>

  <div class="field">
    <%= form.label :is_redeem %>
    <%= form.check_box :is_redeem %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Coupon code</th>
      <th>Shop</th>
      <th>Is redeem</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.coupon_code %></td>
        <td><%= coupon.shop_id %></td>
        <td><%= coupon.is_redeem %></td>
        <td><%= coupon.customer_id %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coupon code:</strong>
  <%= @coupon.coupon_code %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @coupon.shop_id %>
</p>

<p>
  <strong>Is redeem:</strong>
  <%= @coupon.is_redeem %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @coupon.customer_id %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>