config/routes.rb
Rails.application.routes.draw do
  namespace :shopify_app do
    post 'webhooks/receive_customer_create_params'
    post 'webhooks/delete_customer'
    post 'webhooks/order_create'
    
  
  end
  post '/customers/updateinfo',to: "customers#updateinfo"
  resources :coupons
  resources :faq
  resources :customers do
    collection {post :import}
  end
  resources :settings
  root :to => 'home#index'
  get 'home/check_status_of_charge_activation',to: "home#check_status_of_charge_activation"
  get 'billings/check_status_of_charge_activation', to: "billings#check_status_of_charge_activation"
  post '/app_proxy/checkings/check_customer_dob_present', to: "checkings#check_customer_dob_present"
  post '/app_proxy/checkings/check_customer_dob_present_and_update', to: "checkings#check_customer_dob_present_and_update"
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
	belongs_to :shop
	validates_uniqueness_of :shop_id
	validates_presence_of :coupon_exp_date, :birthdaycouponcode, :email_subject, :email_content
	validates_numericality_of :coupon_exp_date, :num_of_customer, :day_number, :greater_than_or_equal_to => 1
	validate :assign_all_if_the_customers_field_is_empty,on: [:create, :update]
	validate :non_zero, on: [:create, :update]

	def non_zero
		if self.day_number == 0
		   self.errors.add(:day_number, "Field can't be zero")
		end
	end
	def assign_all_if_the_customers_field_is_empty
	  num_of_customer
	  regex = /\A[+-]?\d+(\.[\d]+)?\z/
	  if num_of_customer == ''
		self.num_of_customer = 'all'  
	  elsif num_of_customer.strip == 'all'
		#do nothing
	  elsif num_of_customer.to_i < 0
	    self.errors.add(:num_of_customer,'can\'t be negative')				
	  elsif(num_of_customer[/\d+/] == nil) 
	    self.errors.add(:num_of_customer,'Invalid Entry in number of customers field')
	  elsif(!!regex.match(num_of_customer))
	  else
		self.errors.add(:num_of_customer,'Invalid Entry in number of customers field') 
	  end		
	end
end  

app/controllers/settings_controller.rb
# require 'coupon_code_mail_sender.rb'
class SettingsController < ShopifyApp::AuthenticatedController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.where(shop_id: ApplicationHelper.get_shop.id)
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)
    @setting.shop_id = ApplicationHelper.get_shop.id
    # binding.pry
    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        @current_shop = ShopifyAPI::Shop.current
        @domain = @current_shop.myshopify_domain
        @shop = Shop.find_by(shopify_domain: @domain)
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:shop_id, :day_number, :num_of_customer, :coupon_exp_date, :birthdaycouponcode, :email_subject, :email_content)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<style>
.edit_container .form-group {
  margin-bottom: 10px;
}
.edit_container .form-control {
    width: 100%;
    padding: 10px;
    height: auto;
    font-size: 14px;
    color:black;
    background-color:#fff;
    border:1px solid #ccc;
    border-radius:4px;
    line-height:1.42857143;
}

.edit_container {
    text-align: left;
    width: 50%;
    margin: 15px auto;
}
.edit_container .actions input {
    width: 100%;
    color: #fff;
    margin-top: 10px;
    background-color: #1C2260;
    border-color: #1C2260;
}


.edit_container .actions input:hover {
    background: #F2F2F2;
    transition: 0.5s;
    color: #000;
}
.footer_buttons a {
  color: #fff;
  background: #1C2260;
  text-transform: capitalize;
  font-size: 14px;
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-weight: 400;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
  touch-action: manipulation;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
  width:25%;
}
.footer_buttons a:hover {
  background: #F2F2F2;
  transition: 0.5s;
  color:#000;
}

@media only screen and (max-width: 600px) {
  .edit_container {
    width: 100%;
  }
  .footer_buttons a {
      width: 100%;
      margin-bottom: 15px;
}
}
</style>






<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2 style="color:red;"><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <span style="color:red;"><%= message %></span>
      <% end %>
      </ul>
    </div>
  <% end %>


  



<center>
  <div class="container">
    <div class="edit_container">
    <div class="form-group">
      <%= form.label :day_number,'Days before birthday (*)',class: "form-group" %>
      <%= form.number_field :day_number,class: "form-control", min:0 %>
    </div>
      

    <div class="form-group">
      <%= form.label :num_of_customer,'Max number of customers to sent to',class: "form-group" %>
      <%= form.text_field :num_of_customer, class: "form-control", min:0 %>
    </div>
      

    <div class="form-group">
      <%#= form.label :coupon_exp_date,'Coupon Active Till(*)',class: "form-group"%>
      <%= form.hidden_field :coupon_exp_date, class: "form-control", min:0, value: 321 %>
    </div>

    <div class="form-group">
      <%= form.label :birthdaycouponcode,'Birthday Coupon Code(*)',class: "form-group" %>
      <%= form.text_field :birthdaycouponcode , class: "form-control" %>
    </div>
      
      
    
    <div class="form-group">
    <%= form.label :email_subject,'Email subject (*)',class: "form-group" %>
    <%= form.text_area :email_subject, class: "form-control" %>
  </div>
    

  <div class="form-group">
    <%= form.label :email_content,'Email content (*)',class: "form-group" %>
    <%= form.text_area :email_content, class: "form-control" %>
  </div>
    


    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
    </div>
  </div>
  </center>
<% end %>

app/views/settings/edit.html.erb
<style>
.btn-primary
  {
	background-color:#2d2b75;
    color:white;
    text-decoration:none;
    border-radius:4px;
    
  }
  .btn-primary:hover
  {
	background-color:#2d2b75;
    color:white;
  }
  .main-title
  {
    color:#2d2b75;
  }
  .footer_buttons a {
    color: #fff;
    background: #1C2260;
    text-transform: capitalize;
    font-size: 14px;
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
  }
  .footer_buttons a:hover {
    background: #F2F2F2;
    transition: 0.5s;
  }
  </style>

<%= render 'layouts/nav' %>
<center><h1 class="main-title">Editing Setting</h1>

<%= render 'form', setting: @setting %>
<div class = "container">
<div class = "footer_buttons">
<%= link_to 'Show', @setting ,class: "btn btn-primary"%> 
<%= link_to 'Back', settings_path ,class: "btn btn-primary"%>
</div>
</div>
</center>


  

app/views/settings/index.html.erb
<style>
   .colours
   
  {
    background-color:#2d2b75;
    color:white;
  }
  .table{
    box-shadow:8px 10px 18px #888888;
  }
  .main-title
  {
    color: #2d2b75;
    width: 100%;
    margin: 30px auto;
    text-align: center;
}
table {
  border-collapse: collapse;
  width: 100%;
  table-layout: fixed;
}
th, td {
  text-align: left;
  padding: 8px;
}
tr:nth-child(even) {background-color: #F2F2F2;}

table.table.table-hover td {
    padding: 20px;
    font-size: 14px;
}
table.table.table-hover th {
    padding: 20px;
    background: #1C2260;
    color: #fff;
}
table.table.table-hover {
border: 1px solid #ddd;
font-size: 14px;
-webkit-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
}

.footer_buttons a {
    color: #fff;
    background: #1C2260;
    text-transform: capitalize;
    font-size: 14px;
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}
.footer_buttons a:hover {
    background: #F2F2F2;
    transition: 0.5s;
}

</style>

<%= render 'layouts/nav' %>
<p id="notice" style = "color:green;" align = "center"><%= notice %></p>
  <h1 class="main-title">Settings</h1>
  <% @settings.each do |setting| %>
      <div class="container">
      <div style="overflow-x:auto;">
      <table class="table table-hover"> 
      <tbody>
      
            <tr>
            <th>Days Before Birthday</th>
            <td>Before <%= setting.day_number %> days</td>
            </tr>
            <tr>
            <th>Max Number Of Customer To Sent To</th>
            <td><%= setting.num_of_customer %> </td>
            </tr>
            <tr>
            <th>Birthday Coupon Code</th>
            <td><%= setting.birthdaycouponcode %> </td>
            </tr>
            <tr>
            <th>Email subject</th>
            <td><%= setting.email_subject %> </td>
            </tr>
            <tr>
            <th>Email content</th>
            <td><%= setting.email_content %> </td>
            </tr>
           
         
        </tbody>
      </table>
      </div>
      </div>
      <div class = "footer_buttons">
      <center>
              <%= link_to 'Show', setting,class: "btn btn-default" %> 
              <%= link_to 'Edit', edit_setting_path(setting) ,class: "btn btn-default"%> 
              <%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default" %> 
              </center>
              </div>
      <% end %>
      <br>
      <center>
      <% if @settings.count > 0 %>
      <% else %>
        <%= link_to 'New Setting', new_setting_path %>
      <% end %>
      </center>
 

app/views/settings/new.html.erb
<style>
.footer_buttons_new a {
  color: #fff;
  background: #1C2260;
  text-transform: capitalize;
  font-size: 14px;
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-weight: 400;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
  touch-action: manipulation;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
  width: auto;
}
.footer_buttons_new a:hover {
  background: #F2F2F2;
  transition: 0.5s;
  color:#1C2260;
}
</style>
<%= render 'layouts/nav' %>
<center>
	<h1>New Setting</h1>

	<%= render 'form', setting: @setting %> <br>
	<div class = "footer_buttons_new">
		<%= link_to 'Back', settings_path,class: 'btn btn-primary' %>
	</div>
</center>

app/views/settings/show.html.erb
<style>
.table
  {
  box-shadow:8px 10px 18px #888888;
  }
  .btn-default
  {
	background-color:#2d2b75;
    color:white;
  }
  .btn-default:hover
  {
	background-color:#2d2b75;
    color:white;
  }

  table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
  }
  th, td {
    text-align: left;
    padding: 8px;
  }
  tr:nth-child(even) {background-color: #F2F2F2;}
  
  table.table.table-hover td {
      padding: 20px;
      font-size: 14px;
  }
  table.table.table-hover th {
      padding: 20px;
      background: #1C2260;
      color: #fff;
  }
  table.table.table-hover {
  border: 1px solid #ddd;
  font-size: 14px;
  -webkit-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
  -moz-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
  box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.75);
  margin-top:30px;
  }

.footer_buttons a {
  color: #fff;
  background: #1C2260;
  text-transform: capitalize;
  font-size: 14px;
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-weight: 400;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
  touch-action: manipulation;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}
.footer_buttons a:hover {
  background: #F2F2F2;
  transition: 0.5s;
}
</style
<%= render 'layouts/nav' %>
<center>
	<p id="notice" style="color:green;"><%= notice %></p>
  
	<div class="container">
  <table class="table table-hover">
    <tbody>
      <tr>
        <th>Coupon Sent Before </th>
        <td><%= @setting.day_number %> days </td>
        
      </tr>
      <tr>
        <th>Total Customers Who Will Get Coupon </th>
        <td><%= @setting.num_of_customer %> customers </td>
        
      </tr>
      
      <tr>
        <th>Birthday Coupon Code </th>
        <td><%= @setting.birthdaycouponcode %></td>
        
      </tr>
      
      <tr>
        <th>Birthday message title</th>
        <td><%= @setting.email_subject %></td>
        
      </tr>
      
      <tr>
      <th>Birthday message</th>
      <td><%= @setting.email_content %></td>
      
    </tr>
      
      
    </tbody>
  </table>
</div>
<div class = "footer_buttons">
     <%= link_to 'Edit', edit_setting_path(@setting),class: "btn btn-default"  %> 
	 <%= link_to 'Back', settings_path,class: "btn btn-default" %>
</div>
</center>