config/routes.rb
Rails.application.routes.draw do
  namespace :shopify_app do
    post 'webhooks/receive_customer_create_params'
    post 'webhooks/delete_customer'
    post 'webhooks/order_create'
    
  
  end
  post '/customers/updateinfo',to: "customers#updateinfo"
  resources :coupons
  resources :faq
  resources :customers do
    collection {post :import}
  end
  resources :settings
  root :to => 'home#index'
  get 'home/check_status_of_charge_activation',to: "home#check_status_of_charge_activation"
  get 'billings/check_status_of_charge_activation', to: "billings#check_status_of_charge_activation"
  post '/app_proxy/checkings/check_customer_dob_present', to: "checkings#check_customer_dob_present"
  post '/app_proxy/checkings/check_customer_dob_present_and_update', to: "checkings#check_customer_dob_present_and_update"
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one :coupon
  belongs_to :shop
  has_many :orders
  has_many :customer_received_mails, dependent: :delete_all
  # validates_uniqueness_of :shopify_customer_id
  validates_uniqueness_of :customer_email
  validate :correct_date_of_birthday_field, on: :create
  validate :correct_date_of_birthday_field, on: :update


  def self.import(file)

    @shop_id = ApplicationHelper.get_shop.id
    status = {success: false, line:0, record_count: 0}
    CSV.foreach(file.path, headers: true).with_index do |row, index|
      # binding.pry
      if row["customer_email"].class == NilClass || row["birthday"].class == NilClass
        status[:line] = index + 2
        #binding.pry
        #return status
      else
        customer = new
        customer.attributes = row.to_hash
        customer.customer_email = row["customer_email"]
        customer.birthday = row["birthday"]
        customer.shop_id = @shop_id
        # binding.pry
        if customer.save

          if customer.birthday.strftime("%d-%m") == Date.today.strftime("%d-%m")
            #binding.pry
            UserMailer.birthday(customer).deliver!   
          else
            #binding.pry
            CouponCodeMailSender.sending_mails
          end

          status[:record_count] += 1
        else
          # binding.pry
          status[:line] = index + 2
          return status
        end
      end
    end
    status[:success] = true
    return status
  end


  def self.say_hello_to_the_world
    CouponCodeMailSender.new(Shop.first)
  end	

  def correct_date_of_birthday_field
    if(self.birthday > Date.today)
       self.errors.add(:birthday,' The Birthdate is invalid!')   
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ShopifyApp::AuthenticatedController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  layout 'application'
  # skip_before_action :verify_authenticity_token
  # require 'json'
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.where(shop_id: ApplicationHelper.get_shop.id)
  end

  # def prevent_from_corb_and_cors
  #   headers['Access-Control-Allow-Origin'] = request.env['HTTP_ORIGIN']
  #   headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  #   headers['Access-Control-Max-Age'] = '1000'
  #   headers['Access-Control-Allow-Headers'] = '*,x-requested-with'
  # end
 
  # def updateinfo
  #   @data = params
  #   binding.pry
  #   render json: {updated:true,msg:"hi"}, :callback => params[:callback]
  #   prevent_from_corb_and_cors
  # end

  # GET /customers/1
  # GET /customers/1.json

  def import
    if params[:file].class == NilClass
      # binding.pry
      redirect_to customers_path, notice: "Error Encountered, Please select the file"
    else
      status = Customer.import(params[:file])
      if status[:success]
        redirect_to customers_path, notice: "CSV Uploaded Successfully"
      else
        # binding.pry
        redirect_to customers_path, notice: "Error Encountered, Please check the file in row no #{status[:line]}"
      end
    end
  end

  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        UserMailer.birthday(@customer).deliver
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:shopify_customer_id, :customer_name, :customer_email, :shop_id, :birthday)
    end
   
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" style="color:red;">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <center>
  <div class="container-1">
    
    <div class="form-group">
      <%= form.label :shopify_customer_id,class: "form-group" %>
      <%= form.number_field :shopify_customer_id,class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :customer_name,class: "form-group" %>
      <%= form.text_field :customer_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :customer_email ,class: "form-group"%>s
      <%= form.text_field :customer_email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :birthday,class: "form-group" %>
      <%= form.date_field :birthday, class: "form-control" %>
    </div>

    
    <div class="actions">
      <%= form.submit %>
    </div>

  </div>
  </center>
<% end %>

<style>
button, html input[type=button], input[type=reset], input[type=submit]
{
  -webkit-appearance:button;
  cursor:pointer;
  background-color:#2d2d84;
  color:white;
  height:40px;
  border-radius:5px;
}
.form-control
{
  width:31%;
}
</style>

app/views/customers/edit.html.erb
<center><h1 class="main-title">Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer,class:"btn btn-default" %> 
<%= link_to 'Back', customers_path,class:"btn btn-default" %>
</center>

<style>
.main-title
{
    color:#2d2d84;
}
.btn-default
{
    background-color:#2d2d84;
    color:white;
}
.btn-default:hover
{
    background-color:#2d2d84;
    color:white;
}

</style>

app/views/customers/index.html.erb
<style>
.colours

{
 background-color:#2d2b75;
 color:white;
}
.table{
 box-shadow:8px 10px 18px #888888;
}
.main-title
  {
    
    color:#2d2b75;
    width:170px;
  }
  .btn-primary
  {
  background-color:#2d2d84;
  color:white;
  }
  .btn-primary:hover
  {
  background-color:#2d2d84;
  color:white;
  }
  

  a:link_to{
    color:#2d2d84;
  }

  uploadcsv form {
    display: inline-block;
    vertical-align: top;
}
.uploadcsv {
text-align: right;
    margin-bottom: 20px;
    float:right;
    width:27%;
  
}

.uploadcsv h3 {
    font-size: 15px;
    text-transform: uppercase;
    color: #1C2260;
    line-height: 14px;
}

.uploadcsv input#file {
    display: inline-block;
    width: 58%;
    padding: 5px;
    margin-bottom: 0;
    font-size: 12px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
    background: #1C2260;
    color: #fff;
    vertical-align: middle;
}

.uploadcsv input[type="submit"] {
    width: 25%;
    display: inline-block;
    padding: 5px;
    margin-bottom: 0;
    font-size: 13px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
    background: #1C2260;
    color: #fff;
}


.btnfile {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 20px;
  font-weight: bold;
}
.exportcsv a {
  font-size: 12px;
  text-transform: uppercase;
  color: #1C2260;
  line-height: 14px;
  font-weight: 500;
}
.exportcsv {
    margin-top: 10px;
}

</style>


<p id="notice"><%= notice %></p>

<center><h1 class="main-title">Customers</h1></center>

<div class="container">
<div class=" uploadcsv">

<h3> Import customer csv </h3>
<%= form_tag import_customers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload" %>
<% end %>
<div class="exportcsv">
  <%= link_to "View sample customer CSV", "/sample.csv"%>
</div>
</div>
</div>

<div class="container">
  <table class="table table-hover">
    <thead class="colours">
      <tr>
        <th>Customer Email</th>
        <th>Birthday</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    </div>


  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.customer_email %></td>
        <td><%= customer.birthday %></td>
        <td><%= link_to 'Show', customer, class: "btn btn-default"%></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-default"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<center><h1 class="main-title">New Customer</h1></center>

<%= render 'form', customer: @customer %>
<br>
<center><%= link_to 'Back', customers_path, class: "btn btn-primary" %></center>

<style>
.btn-primary:hover
{
    background-color:#2d2d84;
    color:white;

}
.main-title
{
    color:#2d2d84;

}
</style>

app/views/customers/show.html.erb
<p id="notice" style = "color:green;" align = "center"><%= notice %></p>

<center>
<div class="container">
  <table class="table table-hover">
    <tbody>
      <tr>
        <td>Customer Name</td>
        <td><%= @customer.customer_name %></td>
        
      </tr>
      <tr>
        <td>Customer Email</td>
        <td><%= @customer.customer_email %></td>
        
      </tr>
      <tr>
        <td>Birthday</td>
        <td><%= @customer.birthday %></td>
        
      </tr>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_customer_path(@customer),class:"btn btn-default" %> 
  <%= link_to 'Back', customers_path,class:"btn btn-default" %>

</div>

</center>


<style>
.table
{
  box-shadow:8px 10px 18px #888888;
}
.btn-default
{
  background-color:#2d2d84;
  color:#fff;
}
.btn-default:hover
{
  background-color:#2d2d84;
  color:#fff;
}

</style>