config/routes.rb
Rails.application.routes.draw do
  namespace :shopify_app do
    post 'webhooks/receive_customer_create_params'
    post 'webhooks/delete_customer'
    post 'webhooks/order_create'
    
  
  end
  post '/customers/updateinfo',to: "customers#updateinfo"
  resources :coupons
  resources :faq
  resources :customers do
    collection {post :import}
  end
  resources :settings
  root :to => 'home#index'
  get 'home/check_status_of_charge_activation',to: "home#check_status_of_charge_activation"
  get 'billings/check_status_of_charge_activation', to: "billings#check_status_of_charge_activation"
  post '/app_proxy/checkings/check_customer_dob_present', to: "checkings#check_customer_dob_present"
  post '/app_proxy/checkings/check_customer_dob_present_and_update', to: "checkings#check_customer_dob_present_and_update"
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/_nav.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
<style>
body, h1, h2,h3,h4,h5,h6,p,div,a,span, input,table, td, th{ font-weight: 500; font-family: 'Roboto', sans-serif !important;}
p,div,a,span, input, td{ font-weight: 400;}
.app-wrapper {
    overflow: hidden;
}
</style>
<div class="top-bar navbar-default" oncontextmenu="return false;">
    <div class="container" oncontextmenu="return false;">
        <div class="row">
            <div class="col-sm-6">
                <ul class="list-inline">
                    <li><i class="fas fa-envelope"></i><a> apps@kloctechnologies.com</a></li>
                </ul>
            </div>
            <div class="col-sm-6 text-right">
                <ul class="list-inline">
                    <li> <a href="#" target="_blank"><i class="fab fa-twitter-square"></i></a></li>
                    <li> <a href="#" target="_blank"><i class="fab fa-facebook-square"></i></a></li>
                    <li> <a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    <li> <a href="#" target="_blank"><i class="fab fa-google-plus"></i></a></li>
                    <li> <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<nav class="navbar  topnav" role="navigation" oncontextmenu="return false;">
    <div class="container topnav">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#"><img src="https://s3.ap-south-1.amazonaws.com/referral-image-logo/logo.png" alt="" /></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
                <%= link_to "Home", root_path, :class=>"nav-link" %>
              </li>
              <% if session[:status] == "accepted" %>
                    <li class="nav-item">
                        <%= link_to "Shop Settings", settings_path, :class=>"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Customer", customers_path, :class=>"nav-link" %>
                    </li>
              <% end %>
              <li class="nav-item">
                
              <%= link_to "FAQ", faq_index_path, :class=>"nav-link" %>
              </li>
            </ul>
        </div>
    </div>
</nav>
<hr />
<style>
section{padding-bottom:50px;}
a.navbar-brand.topnav {
    height: auto;
}
.top-bar.navbar-default {
    padding: 10px 0;
}
.top-bar.navbar-default ul.list-inline {
    margin: 0;
}
.top-bar.navbar-default {
    padding: 10px 0;
    background: #2d2b75;
    color: #fff;
}
.top-bar.navbar-default a {
    color: #fff;
}
.top-bar.navbar-default a:hover {
    background: none;
    text-decoration: none;
}
a:hover {
    background: none;
    text-decoration: none;
}
nav.navbar.topnav {
    margin: 0 !important;
}
nav.navbar.topnav + hr {
    margin: 10px 0 0;
}
nav.navbar.topnav ul > li a.nav-link {
    padding: 10px 20px;
    color: #000;
    margin: 10px 2px;
}
nav.navbar.topnav ul > li a.nav-link:hover {
    background: #2b2b71;
    color: #fff;
}
.container h3 {
    font-size: 18px;
    margin-bottom: 15px;
    text-transform: capitalize;
}
.col-sm-12 > div > h5 {
    font-size: 14px;
    font-weight: 400;
    background: #2b2b71;
    padding: 12px;
    color:#fff;
    margin-bottom:0;
}
.col-sm-12 > div + div{
    border: 1px solid #2b2b71;
    padding: 15px;
    margin-bottom:50px;
    overflow-x: scroll;
}
table#country_list {
    margin: 0;
}
form#discount_form {
    padding: 25PX 20px;
    border: 1px solid #ddd;
}
h3.form-heading {
    padding: 15px 20px;
    margin: 30px 0 0;
    background: #2b2b71;
    color: #fff;
}
.form-group > span:nth-last-child(1) {
    color: red;
    font-size: 12px;
}
.form-group.typeData {
    position: relative;
}
.typeData span#typeData {
    position: absolute;
    right: 1px;
    top: 1px;
    display: none;
    padding: 6px;
    background: #ccc;
    border-radius: 0 4px 3px 0;
}
#hide-table{display:none}
.navbar-toggle span.icon-bar {
    background: #2b2b71;
}
.tooltip.top .tooltip-inner {
    background-color: black;
  }
.input-color {
    position: relative;
}
.input-color input {
    padding-left: 20px;
}
.input-color .color-box {
    width: 15px;
    height: 15px;
    display: inline-block;
    background-color: #ccc;
    position: absolute;
    left: 5px;
    top: 5px;
}
.table_shadow {
    box-shadow: 0px 0px 40px 0px #0000004d;
    margin: 30px 0 40px 0;
}
.table_shadow thead {
    background: #2d2b75;
    color: #fff;
}
.card_shadow {
    box-shadow: 0px 0px 40px 0px #0000004d;
    margin: 50px 0;
    padding: 30px;
    border-radius: 10px;
}
.card_panel_block {
    box-shadow: 0px 0px 40px 0px #0000004d;
    margin: 50px 0;
    padding: 0px;
    border-radius: 0px;
}
.card_head{
    background: #2d2b75;
    color: #fff;
    text-align: center;
    font-size: 14px;
    text-transform: uppercase;
}
.card_panel_details {
    padding: 10px;
}
.block_shadow {
    box-shadow: 0px 0px 40px 0px #0000004d;
    margin: 10px 0 30px 0;
    padding: 10px;
    border-radius: 10px;
}
.block_shadow h2 {
    margin: 0;
    font-size: 22px;
    text-transform: uppercase;
}
.btn_block {
    border-radius: 0;
    margin: 10px 0;
}
a:hover, a:focus {
    background: none;
    text-decoration: none;
    color: #b1d362;
}
.add_table_margin {
  margin-top: 125px;
  padding: 20px;
}
.btn-primary {
    background-color: #2d2b75;
    border-color: #2d2b75;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BirthdayMail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= session[:name] %>
  '</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: ("https://#{ @shop_session.url }" if @shop_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>